{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.programs.safe-chain;

  defaultTools = [
    "npm"
    "npx"
    "yarn"
    "pnpm"
    "pnpx"
    "rush"
    "rushx"
    "bun"
    "bunx"
    "uv"
    "uvx"
    "pip"
    "pip3"
    "poetry"
    "pipx"
  ];

  pythonTools = [
    "python"
    "python3"
  ];

  tools = lib.unique (cfg.tools ++ lib.optionals cfg.wrapPython pythonTools);
  shimsDir = "${config.home.homeDirectory}/.local/share/safe-chain-nix/shims";
  safeChainArgs = lib.escapeShellArgs cfg.extraArgs;

  mkShim = tool: ''
    #!/bin/sh
    # Generated by safe-chain-nix. It removes this shim directory from PATH
    # before launching safe-chain so the wrapped package manager can be found.

    remove_safe_chain_shim_from_path() {
      _safe_chain_phys=$(CDPATH= cd -- "$(dirname -- "$0")" 2>/dev/null && pwd -P)
      if [ -z "$_safe_chain_phys" ]; then
        echo "$PATH"
        return
      fi

      _path=$(printf '%s' "$PATH" | sed "s|''${_safe_chain_phys}:||g")
      _dir=$(dirname -- "$0")
      case "$_dir" in
        /*) [ "$_dir" != "$_safe_chain_phys" ] && _path=$(printf '%s' "$_path" | sed "s|''${_dir}:||g") ;;
      esac
      echo "$_path"
    }

    if command -v safe-chain >/dev/null 2>&1; then
      PATH=$(remove_safe_chain_shim_from_path) exec safe-chain ${lib.escapeShellArg tool} ${safeChainArgs} "$@"
    fi

    printf '\033[43;30mWarning:\033[0m safe-chain is not available; running %s without protection.\n' ${lib.escapeShellArg tool} >&2
    original_cmd=$(PATH=$(remove_safe_chain_shim_from_path) command -v ${lib.escapeShellArg tool})
    if [ -n "$original_cmd" ]; then
      exec "$original_cmd" "$@"
    fi

    echo "Error: could not find original ${tool}" >&2
    exit 1
  '';
in
{
  options.programs.safe-chain = {
    enable = lib.mkEnableOption "Aikido Safe Chain";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.callPackage ../../pkgs/safe-chain { };
      defaultText = lib.literalExpression "pkgs.callPackage ./pkgs/safe-chain { }";
      description = "Safe Chain package to install.";
    };

    integrationMode = lib.mkOption {
      type = lib.types.enum [
        "cli"
        "wrappers"
      ];
      default = "cli";
      description = ''
        Integration mode. "cli" only installs the safe-chain commands.
        "wrappers" also places package-manager shims early in PATH.
      '';
    };

    tools = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = defaultTools;
      description = "Package manager commands to wrap when integrationMode is \"wrappers\".";
    };

    wrapPython = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Also wrap python and python3 so python -m pip is protected.";
    };

    extraArgs = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [ "--safe-chain-skip-minimum-package-age" ];
      description = "Extra Safe Chain arguments to pass before the package manager arguments.";
    };
  };

  config = lib.mkIf cfg.enable (
    lib.mkMerge [
      {
        home.packages = [ cfg.package ];
      }

      (lib.mkIf (cfg.integrationMode == "wrappers") {
        home.sessionPath = [ shimsDir ];

        home.file = lib.listToAttrs (
          map (tool: {
            name = ".local/share/safe-chain-nix/shims/${tool}";
            value = {
              executable = true;
              text = mkShim tool;
            };
          }) tools
        );
      })
    ]
  );
}
